=== seasidesparrow/fulltext_data_model/json_schema/Document.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/adsabs/fulltext_data_model/refs/heads/prototype/adsfulltextschema/Document.json",
  "title": "Document",
  "description": "Data schema for importing fulltext data into Honeycomb",
  "type": "object",
  "properties": {
    "abstract": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Abstract.json objects.",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Abstract.json"
      }
    },
    "acknowledgements": {
      "$ref": "./Acknowledgements.json"
    },
    "appendices": {
      "type": "array",
      "description": "Array of Section.json objects.",
      "items": {
        "$ref": "./Section.json"
      }
    },
    "authors": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Contrib.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Contrib.json"
      }
    },
    "body": {
      "type": "array",
      "description": "Array of Section.json objects",
      "items": {
        "$ref": "./Section.json"
      }
    },
    "copyright": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean"
        },
        "statement": {
          "type": "string"
        }
      }
    },
    "dataavailability": {
      "$ref": "./DataAvailability.json"
    },
    "footnote-table": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Footnote.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Footnote.json"
      }
    },
    "funding": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Funder.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Funder.json"
      }
    },
    "keywords": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Keyword.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Keyword.json"
      }
    },
    "language": {
      "type": "string",
      "description": "ISO-639-1 country code of document language declaration"
    },
    "openAccess": {
      "description": "ingest_data_model/json_schema/OpenAccess.json object",
      "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/OpenAccess.json"
    },
    "otherContributor": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Contrib.json / role pairs",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/OtherContrib.json"
      }
    },
    "persistentIDs": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/PersistentID.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/PersistentID.json"
      }
    },
    "pubDate": {
      "description": "ingest_data_model/json_schema/PubDates.json object",
      "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/PubDates.json"
    },
    "publication": {
      "description": "ingest_data_model/json_schema/Publication.json object",
      "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Publication.json"
    },
    "recordData": {
      "description": "ingest_data_model/json_schema/RecordData.json object",
      "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/RecordData.json"
    },
    "references": {
      "type": "array",
      "description": "Array of Reference.json objects",
      "items": {
        "$ref": "./Reference.json"
      }
    },
    "subtitle": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Title.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Title.json"
      }
    },
    "supplementaryMaterial": {
      "type": "array",
      "description": "Array of text objects",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "type": "array",
      "description": "Array of ingest_data_model/json_schema/Title.json objects",
      "items": {
        "$ref": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.1/json_schema/Title.json"
      }
    }
  },
  "required": [
    "recordData",
    "body",
    "title",
    "pubDate",
    "publication"
  ],
  "additionalProperties": false
}

=== seasidesparrow/fulltext_data_model/test_data/aa53501-24.xml.json
{
  "abstract": [
    {
      "atext": "Context. Dense filaments, also known as feathers, are kiloparsec-scale dusty features present in nearby main sequence galaxies. Distinct from the spiral arms, filaments constitute a major portion of dense gas concentration. They are expected to play an important role in star formation and are known to harbour embedded star-forming regions and H\u2006II regions. Aims. We explore the origin of filaments and feathers in disc galaxies via global gravitational instability. Methods. We conduct a parameter study using three-dimensional hydrodynamical simulations of isolated disc galaxies that are isothermal, self-gravitating and are initialised in equilibrium. Our galaxies are uniquely characterised by two dimensionless parameters, the Toomre Q and the rotational Mach number, \u2133c\u2004=\u2004vc/cs (ratio of circular velocity to sound speed). We carry out simulations covering a wide range in both parameters. Results. We find that galaxies with Q\u2004=\u20041 form filaments within a single rotation, while galaxies with Q\u2004\u2265\u20042 do not, even within a couple of rotations. These filaments are kiloparsec long and are semi-regularly spaced along the azimuth of the galaxy. Their morphology, density contrast and formation timescale vary with \u2133c, with filament spacing and instability onset time both inversely proportional to \u2133c and the density contrast increasing with \u2133c. However, filament growth rates in all Q\u2004=\u20041 galaxies are \u223c0.5\u2006\u03a9, where \u03a9 is the angular frequency. We compare the filament spacing in our simulations with the ones in JWST/Mid-Infrared Instrument and HST observations of nearby galaxies and find them to be in agreement. Conclusions. Our study suggests that self-gravity and rotation alone are sufficient to form filaments and feathers, even in the absence of spiral arms or magnetic fields. The morphologies of the resulting filaments are determined primarily by \u2133c, which parametrises the importance of thermal versus rotational support.",
      "language": "en"
    }
  ],
  "acknowledgements": {
    "text": "R. A. acknowledges funding by the Hamburg State Graduate Funding Program (HmbNFG) and heartfully thanks Sharon Meidt, Shivan Khullar, and Chris Matzner for insightful discussions and their enthusiasm. C. F. acknowledges funding provided by the Australian Research Council (Discovery Project grants DP230102280 and DP250101526), and the Australia-Germany Joint Research Cooperation Scheme (UA-DAAD). M. R. K. acknowledges support from the Australian Research Council through Laureate Fellowship FL220100020. We further acknowledge high-performance computing resources provided by the Leibniz Rechenzentrum and the Gauss Centre for Supercomputing (grants pr32lo, pr48pi and GCS Large-scale project 10391), the Australian National Computational Infrastructure (grants ek9 and jh2) and the Pawsey Supercomputing Centre (projects pawsey0807 and pawsey0810) in the framework of the National Computational Merit Allocation Scheme and the ANU Merit Allocation Scheme. The simulation software, FLASH, was in part developed by the Flash Centre for Computational Science at the University of Chicago and the Department of Physics and Astronomy at the University of Rochester."
  },
  "appendices": [
    {
      "atext": "Here, we determine the stellar plus dark matter potential \u03d5dm such that our disc is in radial equilibrium. In a reference frame that co-rotates with the disc angular frequency \u03a9 at a given position (R,\u2006z), radial equilibrium demands that the sum of the gravitational, pressure, and centrifugal forces vanish. We can express this condition as (A.1) \u03c1 \u2202 \u2202 R \u03d5 dm + \u03d5 g + c s 2 \u2202 \u03c1 \u2202 R \u2212 \u03c1 \u03a9 2 R = 0 , $$ \\begin{aligned} \\rho \\frac{\\partial }{\\partial R}\\left(\\phi _{\\rm dm} + \\phi _{\\rm g}\\right) + {c_{\\rm s}}^2 \\frac{\\partial \\rho }{\\partial R} - \\rho \\Omega ^2 R = 0, \\end{aligned} $$ where \u03d5g is the potential due to disc self-gravity, which is given by Wang et al. (2010, their equation 29) (A.2) \u03d5 g = 4 \u03c0 G \u03a3 \u00b0 R d y 2 I 0 ( y ) K 0 ( y ) \u2212 I 1 ( y ) K 1 ( y ) , $$ \\begin{aligned} \\phi _{\\rm g} = 4\\pi G \\Sigma _\\circ {R_{\\rm d}} y^2 \\left[I_0(y) K_0(y) - I_1(y) K_1(y)\\right], \\end{aligned} $$ where y\u2004=\u2004R/2Rd and I0, K0, I1, and K1 are the modified Bessel functions of the first and second kind, of order zero and one. To proceed we must now make some assumptions about the vertical structure of the disc and potential. We start by assuming that the radial variation in density is approximately exponential, \u03c1(R)\u221dexp(\u2212R/Rd). This assumption is exact only if the disc vertical profile is independent of radius, but is true approximately as long as the disc scale height does not vary on scales \u226aRd; since this term is highly sub-dominant in any event (roughly 100\u00d7 smaller than the centrifugal term), we do not seek a more accurate approximation. Finally, at the midplane we require that \u03a9\u2004=\u2004vrot/R, but we must make an assumption about the variation of \u03a9 in the z direction, or, equivalently, assume a shape for the centrifugal potential \u03c8, where \u2202\u03c8/\u2202R\u2004=\u2004\u03a92R. For this purpose we adopt the flattened centrifugal potential form suggested by Binney & Tremaine (1987), (A.3) \u03c8 = v c 2 2 ln 1 R c 2 R 2 + R c 2 + z q 2 , $$ \\begin{aligned} \\psi = \\frac{{v_{\\rm c}} ^{2}}{2} \\ln \\left\\{ \\frac{1}{R_{\\rm c} ^{2}} \\left[ R^2 + R_{\\rm c}^2 + \\left( \\frac{z}{q} \\right)^2 \\right] \\right\\} , \\end{aligned} $$ where q is a dimensionless parameter that determines the amount of flattening. One can readily verify that this potential satisfies our condition that \u2202\u03c8/\u2202R\u2004=\u2004\u03a92R. Following Binney & Tremaine\u2019s estimates for realistic galactic potentials, we adopt q\u2004=\u20040.7. With these assumptions, our equation of force balance reduces to (A.4) \u03c1 \u2202 \u2202 R \u03d5 dm + \u03d5 g \u2212 c s 2 R R d \u2212 \u03c8 = 0 , $$ \\begin{aligned} \\rho \\frac{\\partial }{\\partial R}\\left(\\phi _{\\rm dm} + \\phi _{\\rm g} - {c_{\\rm s}}^2 \\frac{R}{R_d} - \\psi \\right) = 0, \\end{aligned} $$ which has the immediate solution (A.5) \u03d5 dm = \u03c8 \u2212 \u03d5 g + c s 2 R R d . $$ \\begin{aligned} \\phi _{\\rm dm} = \\psi - \\phi _{\\rm g} + {c_{\\rm s}}^2 \\frac{R}{{R_{\\rm d}}}. \\end{aligned} $$ We have therefore succeeded in identifying the stellar plus dark matter potential required to place the disc in equilibrium.",
      "bibrefs": [
        {
          "atext": "Wang et al. (2010",
          "id": "R59"
        },
        {
          "atext": "Binney & Tremaine (1987)",
          "id": "R2"
        }
      ],
      "footnotes": [
        {
          "id": "FN3",
          "label": "2",
          "text": ""
        }
      ],
      "id": "APP1",
      "label": "Appendix A:",
      "section_title": "Dark matter potential"
    },
    {
